gText_Birch_Welcome::
	.string "Greetings!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Lady Sincona.\p"
	.string "But I prefer to be known as the\n"
	.string "Pokémon Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "And this is a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "The world is teeming with the\n"
	.string "creatures we call Pokémon.\p"
	.string "We depend on Pokémon in a myriad\n"
	.string "of ways.\p"
	.string "Some of us think of them as friends.\l"
	.string "While others train them for battle\n"
	.string "or work with them to make a living.\p"
	.string "It's my dream to research Pokémon\n"
	.string "and find ways to help them.\p"
	.string "Not just here on Salven Island\n"
	.string "but throughout the world.\p"
	.string "But before we embark on this mission,\n"
	.string "I want to know about you.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Tell me about yourself.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Delightful!\p"
	.string "Together {PLAYER}{KUN}, we might just\n"
	.string "change life on this island!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Very well! Then get ready to set off \n"
	.string "on your grand adventure where dreams,\l"
	.string "joy and friendships await you!\p"
	.string "To start off, {PLAYER}{KUN},\n"
	.string "I have a simple mission for you.\l"
	.string "First, you need to wake up!\p"
	.string "{PLAYER}?\p"
	.string "I said wake up this very instant!\p"
	.string "$"
