gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} was stored in the\n"
	.string "Reserve Box.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} was stored in the\n"
	.string "Reserve Box.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "Box “{STR_VAR_3}” in the\n"
	.string "Reserve Box was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "Box “{STR_VAR_3}” in the\n"
	.string "Reserve Box was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "There's no more room for Pokémon!\p"
	.string "The Reserve Box is full and\n"
	.string "can't store any more!$"

gText_NicknameThisPokemon::
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
